"""Build the portable film library, script and launch copy. No network or sending."""
from pathlib import Path
from html import escape
from email.message import EmailMessage
from email.policy import SMTP
import json

K = Path(__file__).resolve().parents[1]
D = json.loads((K/'source/edit.json').read_text(encoding='utf-8'))
EMAIL = 'JEThomasPhD@gmail.com'
BASE = 'https://thomasbroadside.co/'
links = {channel: BASE+'press.html?utm_source='+channel+'&utm_medium='+('email' if channel=='email' else 'social')+'&utm_campaign=history-directors-cut#inside-the-shop' for channel in ('instagram','facebook','linkedin','email')}
(K/'links.json').write_text(json.dumps(links,indent=2)+'\n',encoding='utf-8')
script = '# History has a pulse.\n\n## The director’s cut / 75 seconds\n\nThe press makes words public. The words become part of a life.\n\n'
script += '| Time | Picture | Narration begins |\n|---|---|---|\n'
for s in D['scenes']:
    words=' '.join(v['text'] for v in D['narration'] if s['at']<=v['at']<s['at']+s['duration'])
    script += f'| {s["at"]:g}–{s["at"]+s["duration"]:g}s | {s["label"]} / {s["title"]} | {words or "Score and/or actual machinery."} |\n'
script += '\n## Full narration\n\n'+'\n\n'.join(v['text'] for v in D['narration'])+'\n'
script += '\n## Picture and sound\n\n13 unique shots; 25.5 seconds of actual shop imagery. The opening holds the first Heidelberg frame for 3.5 seconds before its 5.5 seconds of motion and synchronized sound begin at real speed; the finishing equipment appears once later. Each scene appears once. All formats carry the same complete narrative. Elias speaks in separately timed phrases. After “just listen,” four seconds of unaccompanied machinery precede the score. Three custom book-cover designs identify Homer, Matthew and Dante; they are contemporary campaign designs, not historical facsimiles. Actual machinery returns with each shop shot; music and machinery duck under the narrator. Captions are separate and off by default.\n'
(K/'SCRIPT.md').write_text(script,encoding='utf-8')
cards=[]
for fmt,label,size,use in [('wide','The landscape master','1920 × 1080','Website, LinkedIn, presentations'),('vertical','The portrait edition','1080 × 1920','Reels, Stories, mobile'),('square','The square edition','1080 × 1080','Facebook and LinkedIn feed')]:
    file=f'films/history-has-a-pulse-directors-cut-75s-{fmt}.mp4'
    cards.append(f'''<article><video controls playsinline preload="none" poster="artwork/poster-{fmt}.jpg"><source src="{file}" type="video/mp4"><track kind="captions" src="films/directors-cut-75s.vtt" label="English" srclang="en"></video><p class="k">75 SECONDS / {size}</p><h2>{label}</h2><p>{use}. Complete narration, score, and the sounds of the shop.</p><a download href="{file}">Download film ↗</a> · <a download href="artwork/poster-{fmt}.jpg">Cover ↗</a></article>''')
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>History has a pulse. — The director’s cut</title><style>
@font-face{font-family:Caslon;src:url(source/fonts/LibreCaslonDisplay-400.woff2)}@font-face{font-family:Mono;src:url(source/fonts/IBMPlexMono-400.woff2)}*{box-sizing:border-box}body{margin:0;background:#f1ece0;color:#201a10;font:18px/1.7 Georgia,serif}a{color:inherit;text-underline-offset:5px}a:hover{color:#9e3123}header,footer{margin:0 5%;padding:28px 0;border-bottom:1px solid #201a1040;font:12px/1.8 Mono,monospace}header{display:flex;justify-content:space-between;gap:20px}.hero{padding:70px 5% 55px;display:grid;grid-template-columns:1fr 1fr;gap:65px;align-items:center}.hero img{width:100%;display:block}h1{font:clamp(70px,7vw,118px)/.97 Caslon,Georgia,serif;margin:20px 0 30px}h2{font:36px/1.1 Caslon,Georgia,serif;margin:16px 0}.k{font:11px/1.7 Mono,monospace;letter-spacing:1.4px;color:#9e3123}.hero p{max-width:610px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:32px;padding:50px 5%;border-top:1px solid #201a1040}video{display:block;width:100%;height:300px;object-fit:contain;background:#201a10}.grid p{font-size:15px}.grid a{font:12px Mono,monospace}.papers{padding:45px 5%;border-top:1px solid #201a1040;display:grid;grid-template-columns:1fr 1fr;gap:55px}.papers p{font-size:16px}footer{padding:40px 0 60px;border-top:1px solid #201a1040;border-bottom:0}:focus-visible{outline:2px solid #9e3123;outline-offset:5px}@media(max-width:800px){header{display:block}.hero,.grid,.papers{grid-template-columns:1fr;gap:35px}.hero{padding-top:45px}video{height:auto;max-height:65vh}.hero h1{font-size:78px}}
</style></head><body><header><b>THOMAS BROADSIDE CO.</b><span>THE DIRECTOR’S CUT / SEPTEMBER 2026</span></header><main><section class="hero"><div><p class="k">SEVENTY-FIVE SECONDS. ONE CONTINUING STORY.</p><h1>History has<br>a pulse.</h1><p>The press makes words public.<br>The words become part of a life.</p><p>Our Austin presses, the founding story, and the Western Canon—woven into a film about words worth carrying forward.</p><p class="k">25½ SECONDS IN THE REAL SHOP · 13 DISTINCT SHOTS<br>A NEW VOICE · AN ORIGINAL SCORE</p></div><img src="artwork/inked-type.png" alt="Contemporary reconstruction of inked metal type on an eighteenth-century printer’s bench"></section><section class="grid">'''+''.join(cards)+'''</section><section class="papers"><div><h2>Ready for release.</h2><p><a href="CAMPAIGN.md">Launch copy and channel guide ↗</a><br><a href="email/launch-preview.html">Preview the launch email ↗</a> · <a download href="email/launch.eml">Unsent email draft ↗</a><br><a href="films/directors-cut-75s.srt">SRT captions ↗</a> · <a href="films/directors-cut-75s.vtt">WebVTT captions ↗</a></p><p>Captions start off in every player. They remain available through the player’s caption menu.</p></div><div><h2>The working record.</h2><p><a href="SCRIPT.md">Script and scene ledger ↗</a><br><a href="PROVENANCE.md">Images, sound, sources and generation record ↗</a><br><a href="source/endcard.html">Editable closing composition ↗</a><br><a href="manifest.json">Asset checksums ↗</a></p><p>The historical scenes are contemporary reconstructions. Canon settings are visual meditations. Product designs are unchanged. See the production record for the exact source of every shot.</p></div></section></main><footer>WORDS TO LIVE WITH.<br>Thomas Broadside Co. · A venture of Thomas Graphics Inc.<br>9501 N Interstate Hwy 35, Austin, TX 78753<br><a href="mailto:JEThomasPhD@gmail.com">JEThomasPhD@gmail.com</a></footer></body></html>'''
(K/'index.html').write_text(html,encoding='utf-8')

subject='History has a pulse. Just listen.'
paragraphs=['A working press. A sheet sent into the world. Words that become part of a life.', 'Our new 75-second film brings together the presses in our Austin shop, the story of the first printed Declaration, and the Western Canon. The machinery is ours. The historical scenes are contemporary reconstructions. The invitation is simple: read the words, keep the source, and give the enduring a place in your room.', 'Watch History has a pulse. Then explore the broadsides behind the story.']
url=links['email'];unsub='mailto:'+EMAIL+'?subject=Unsubscribe%20from%20Thomas%20Broadside%20Co.'
body=''.join('<p style="margin:0 0 22px;font:17px/1.75 Georgia,serif;color:#201a10">'+escape(p)+'</p>' for p in paragraphs)
letter=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{subject}</title></head><body style="margin:0;background:#e9e2d0"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="600" style="width:100%;max-width:600px;background:#f1ece0" cellspacing="0" cellpadding="0"><tr><td style="padding:32px;font:13px/1.6 'Courier New',monospace;letter-spacing:2px;color:#201a10">THOMAS BROADSIDE CO.</td></tr><tr><td><a href="{escape(url)}"><img src="https://thomasbroadside.co/media/press/history-has-a-pulse-poster-v3.jpg" width="600" alt="History has a pulse. The director’s cut. Our Heidelberg press in motion." style="display:block;width:100%;height:auto;border:0"></a></td></tr><tr><td style="padding:32px"><p style="font:11px/1.6 'Courier New',monospace;letter-spacing:1px;color:#9e3123">THE DIRECTOR’S CUT / 75 SECONDS</p><h1 style="font:normal 42px/1.1 Georgia,serif;color:#201a10">From the press.<br>Into a life.</h1>{body}<table role="presentation" cellspacing="0" cellpadding="0"><tr><td bgcolor="#201a10" style="padding:16px 20px"><a href="{escape(url)}" style="font:13px/1.5 'Courier New',monospace;color:#faf6ea;text-decoration:none">Watch the director’s cut →</a></td></tr></table><p style="font:italic 16px/1.7 Georgia,serif;color:#201a10;margin-top:28px">The Shop Desk<br>Thomas Broadside Co.</p></td></tr><tr><td style="padding:28px 32px;border-top:1px solid #c3b8a3;font:12px/1.7 Georgia,serif;color:#675b47">WORDS TO LIVE WITH.<br>Thomas Broadside Co. · A venture of Thomas Graphics Inc.<br>9501 N Interstate Hwy 35, Austin, TX 78753<br><a href="mailto:{EMAIL}" style="color:#675b47">{EMAIL}</a><br><br>You asked to hear from the shop.<br><a href="{unsub}" style="color:#675b47">Unsubscribe by email</a></td></tr></table></td></tr></table></body></html>'''
plain=subject+'\n\n'+'\n\n'.join(paragraphs)+'\n\nWatch the director’s cut:\n'+url+f'\n\nThe Shop Desk\nThomas Broadside Co.\n9501 N Interstate Hwy 35, Austin, TX 78753\n{EMAIL}\n\nTo unsubscribe, reply with Unsubscribe.\n'
e=K/'email';e.mkdir(exist_ok=True)
(e/'launch.html').write_text(letter,encoding='utf-8');(e/'launch.txt').write_text(plain,encoding='utf-8');(e/'launch-preview.html').write_text(letter.replace('https://thomasbroadside.co/media/press/history-has-a-pulse-poster-v3.jpg','../artwork/poster-wide.jpg'),encoding='utf-8')
msg=EmailMessage(policy=SMTP);msg['Subject']=subject;msg['From']=f'Thomas Broadside Co. <{EMAIL}>';msg['Reply-To']=EMAIL;msg['List-Unsubscribe']='<'+unsub+'>';msg['X-Unsent']='1';msg.set_content(plain)
msg.add_alternative(letter.replace('https://thomasbroadside.co/media/press/history-has-a-pulse-poster-v3.jpg','cid:director-poster'),subtype='html')
msg.get_payload()[-1].add_related((K/'artwork/poster-wide.jpg').read_bytes(),maintype='image',subtype='jpeg',cid='<director-poster>')
(e/'launch.eml').write_bytes(msg.as_bytes())
print('Built director’s cut library, script, tracked links and unsent launch email.')
