"""Build three unsent email drafts, with HTML/text and embedded-image EML.
No recipients, credentials, external service calls, or sends.
"""
from pathlib import Path
from email.message import EmailMessage
from email.policy import SMTP
from html import escape
K=Path(__file__).resolve().parents[1]; EMAIL='JEThomasPhD@gmail.com'; BASE='https://thomasbroadside.co/'
letters=[('words-to-live-with', 'Make room for the enduring.', 'Introducing Words to Live With', 'Some words deserve a place in the room.', ['A homecoming. A blessing. A question about the soul. A prayer for rest. A path through the dark.', 'Our Western Canon room brings together Homer, the Gospel of Matthew, Augustine, Dante, Rembrandt and Blake. Each work keeps its own voice, with its source and translation close at hand.', 'The new reading room includes a quiet 70-second film, narrated by Miriam, and a path into eight works from our collection. The landscapes are contemporary visual meditations; the printed sheets are the designs we make in Austin.', 'Read slowly. Return often. Give the words a place in your life.'], 'Enter the reading room', 'canon.html'), ('the-five-sheet-set', 'Five texts. A considered collection.', 'The Western Canon Set', 'Give the words a home.', ['The Western Canon Set gathers five texts: The Odyssey, The Beatitudes, What is a man profited?, Our heart is restless, and Midway upon the journey.', 'Homer begins a story of homecoming. Matthew preserves the blessings and the question about the soul. Augustine addresses God in prayer. Dante names the dark wood at the beginning of his journey.', 'These works remain distinct. The source and translation accompany each sheet, so a passage can lead back to the fuller work.', 'Explore the set for its available formats. The three art reproductions after Rembrandt and Blake are offered separately.'], 'Explore the five-sheet set', 'documents/the-western-canon-set.html'), ('reading-room-partners', 'A place for lasting words.', 'For libraries, classrooms and reading rooms', 'Bring the works into the room.', ['Thomas Broadside Co. makes contemporary broadsides and art reproductions in Austin, Texas. Our Western Canon collection holds eight works drawn from Homer, Matthew, Augustine, Dante, Rembrandt and Blake.', 'The collection is accompanied by a new reading room: a short film, passages with their named translations, museum records, and links to each printed work.', 'For a library display, classroom, reading space or considered gift, write us with quantities, formats and timing. We can help you choose from the collection.', 'The five-sheet Western Canon Set gathers the texts. The art reproductions are available separately.'], 'Explore the Western Canon', 'canon.html')]
for slug,subject,kicker,heading,paragraphs,cta,target in letters:
    utm=f'utm_source=email&utm_medium=email&utm_campaign=words-to-live-with&utm_content={slug}'
    url=BASE+target+'?'+utm;film=BASE+'canon.html?'+utm;unsub='mailto:'+EMAIL+'?subject=Unsubscribe%20from%20Thomas%20Broadside%20Co.'
    body=''.join('<p style="margin:0 0 21px;font:17px/1.75 Georgia,serif;color:#201a10">'+escape(p)+'</p>' for p in paragraphs)
    html=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(subject)}</title><body style="margin:0;background:#e9e2d0"><div style="display:none;max-height:0;overflow:hidden">Words to Live With. Make room for the enduring.</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#f1ece0"><tr><td style="padding:32px;font:13px/1.5 'Courier New',monospace;letter-spacing:2px;border-bottom:1px solid #c3b8a3">THOMAS BROADSIDE CO.</td></tr><tr><td><a href="{escape(film)}"><img src="https://thomasbroadside.co/media/canon/share-card.jpg" width="600" alt="Words to Live With. Make room for the enduring." style="display:block;width:100%;height:auto;border:0"></a></td></tr><tr><td style="padding:34px 32px"><p style="font:11px/1.6 'Courier New',monospace;letter-spacing:1px;color:#9e3123;text-transform:uppercase">{escape(kicker)}</p><h1 style="font:normal 38px/1.13 Georgia,serif;color:#201a10;margin:20px 0 28px">{escape(heading)}</h1>{body}<table role="presentation" cellpadding="0" cellspacing="0"><tr><td bgcolor="#9e3123" style="padding:16px 20px"><a href="{escape(url)}" style="font:13px/1.4 'Courier New',monospace;text-decoration:none;color:#faf6ea">{escape(cta)} →</a></td></tr></table><p style="font:14px/1.7 Georgia,serif;margin:25px 0"><a href="{escape(film)}#sources" style="color:#9e3123">Read the source notes and the film transcript</a></p><p style="font:italic 16px/1.6 Georgia,serif">The Shop Desk<br>Thomas Broadside Co.</p></td></tr><tr><td style="padding:25px 32px;border-top:1px solid #c3b8a3;font:12px/1.7 Georgia,serif;color:#675b47"><strong>BUILD SOMETHING THAT LASTS</strong><br>Thomas Broadside Co. · A venture of Thomas Graphics Inc.<br>9501 N Interstate Hwy 35, Austin, TX 78753<br><a href="mailto:{EMAIL}" style="color:#675b47">{EMAIL}</a><br><br>Room and landscapes are contemporary visual meditations. Texts retain their named sources and translations.<br><a href="{unsub}" style="color:#675b47">Unsubscribe by email</a></td></tr></table></td></tr></table></body></html>'''
    plain=subject+'\n'+kicker+'\n\n'+'\n\n'.join(paragraphs)+f'\n\n{cta}: {url}\n\nSources and film: {film}\n\nThe Shop Desk\nThomas Broadside Co.\n9501 N Interstate Hwy 35, Austin, TX 78753\n{EMAIL}\n\nRoom and landscapes are contemporary visual meditations.\nTo unsubscribe, reply with Unsubscribe.\n'
    (K/'email'/f'{slug}.html').write_text(html,encoding='utf-8');(K/'email'/f'{slug}-preview.html').write_text(html.replace('https://thomasbroadside.co/media/canon/share-card.jpg','../social/11-share.png'),encoding='utf-8');(K/'email'/f'{slug}.txt').write_text(plain,encoding='utf-8')
    msg=EmailMessage(policy=SMTP);msg['Subject']=subject;msg['From']=f'Thomas Broadside Co. <{EMAIL}>';msg['Reply-To']=EMAIL;msg['X-Unsent']='1';msg['List-Unsubscribe']='<'+unsub+'>';msg.set_content(plain)
    msg.add_alternative(html.replace('https://thomasbroadside.co/media/canon/share-card.jpg','cid:wtlw-hero'),subtype='html')
    msg.get_payload()[-1].add_related((K/'source/email-header.jpg').read_bytes(),maintype='image',subtype='jpeg',cid='<wtlw-hero>')
    (K/'email'/f'{slug}.eml').write_bytes(msg.as_bytes())
print('Three Western Canon email sets exported.')
